const DATA={players:[],stats:{},summary:null,daily:null,schedule:null,transactions:null,career:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const headshot=(id,minor=false)=>`https://img.mlbstatic.com/mlb-photos/image/upload/c_fill,g_auto,w_600,q_auto:best,f_auto/v1/people/${id}/headshot/${minor?'milb/':'67/'}current`;
const logo=id=>id?`https://www.mlbstatic.com/team-logos/${id}.svg`:'';
const levels=['MLB','Triple-A','Double-A','High-A','Single-A','Rookie','Awaiting Pro Assignment','Free Agent'];
function normalizedLevel(p){if(p.status==='fa')return'Free Agent';if(p.status==='mlb')return'MLB';let s=`${p.recentLevel||''} ${p.statusLabel||''}`.toLowerCase();if(s.includes('triple'))return'Triple-A';if(s.includes('double'))return'Double-A';if(s.includes('high'))return'High-A';if(s.includes('single')||s.includes('low-a'))return'Single-A';if(/rookie|acl|fcl|dsl/.test(s))return'Rookie';return'Awaiting Pro Assignment'}
function merge(){DATA.players=DATA.players.map(p=>{let f=DATA.stats[String(p.mlbId)]||{};return{...p,...f,stats:{...(p.stats||{}),...(f.stats||{})}}})}
async function loadAll(){let names=['players','stats','nightly_summary','daily_article','today_schedule','transactions','career_mlb'];let vals=await Promise.all(names.map(n=>fetch(`${n}.json?v=${Date.now()}`,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)));DATA.players=vals[0]?.players||[];DATA.stats=vals[1]?.players||{};DATA.summary=vals[2];DATA.daily=vals[3];DATA.schedule=vals[4];DATA.transactions=vals[5];DATA.career=vals[6]||{players:[]};merge()}
function portrait(p,cls=''){return`<div class="portrait ${cls}"><img src="${headshot(p.mlbId)}" data-alt="${headshot(p.mlbId,true)}" alt="${esc(p.name)} headshot" onerror="if(!this.dataset.tried){this.dataset.tried='1';this.src=this.dataset.alt}else{this.style.display='none';this.nextElementSibling.style.display='grid'}"><span class="portrait-fallback">${esc(p.initials||'CP')}</span></div>`}
function orders(p){return p.type==='hitter'?['AB','R','H','2B','3B','HR','RBI','BB','SO','SB','CS','AVG','OBP','SLG','OPS']:['IP','R','ER','BB','SO','H','ERA','WHIP']}
function playerCard(p){return`<article class="player-card"><div class="player-top">${portrait(p)}<div><div class="player-name">${esc(p.name)}</div><div class="assignment"><b>${esc(p.position)}</b><br>${esc(p.recentTeam||p.team)} · ${esc(normalizedLevel(p))}</div><span class="level-badge">${esc(p.statusLabel||normalizedLevel(p))}</span></div>${p.teamId?`<img class="team-logo" src="${logo(p.teamId)}" alt="">`:''}</div><div class="stats ${p.type==='pitcher'?'pitcher':''}">${orders(p).map(k=>`<div class="stat"><b>${esc(p.stats?.[k]??'—')}</b><small>${k}</small></div>`).join('')}</div><div class="player-note">${esc(p.note||'')}</div><div class="card-actions"><a href="player.html?id=${p.mlbId}">View Mustang profile</a>${p.profileUrl?`<a href="${esc(p.profileUrl)}" target="_blank" rel="noopener">Official profile ↗</a>`:''}</div></article>`}
function awardCard(a){let p=DATA.players.find(x=>String(x.mlbId)===String(a.playerId))||DATA.players.find(x=>x.name===a.player);return`<div class="award">${p?portrait(p,'award-photo'):''}<div class="award-copy"><small>${esc(a.label)}</small><strong>${esc(a.player)}</strong>${a.team?`<em>${esc(a.team)}</em>`:''}<span>${esc(a.line||'')}</span></div></div>`}
function highlightCard(h){return`<article class="highlight"><div class="video-wrap"><video controls preload="metadata" poster="${esc(h.image||'')}"><source src="${esc(h.url)}"></video></div><div><b>${esc(h.title)}</b><p>${esc(h.player)}</p><a href="${esc(h.url)}" target="_blank" rel="noopener">Open official video ↗</a></div></article>`}
function leaderCard(label,p,k){if(!p)return`<div class="leader-card untracked"><small>${label}</small><b>Not tracked yet</b></div>`;return`<div class="leader-card">${portrait(p,'leader-portrait')}<div class="leader-copy"><small>${label}</small><b>${esc(p.name)}</b><strong>${esc(p.stats[k])} ${k}</strong><span class="meta">${esc(p.recentTeam||p.team)} · ${esc(normalizedLevel(p))}</span></div>${p.teamId?`<img class="team-logo" src="${logo(p.teamId)}" alt="">`:''}</div>`}
function leaders(){let hitters=DATA.players.filter(p=>p.type==='hitter'&&p.status!=='fa'),pitchers=DATA.players.filter(p=>p.type==='pitcher'&&p.status!=='fa');let n=v=>{let x=parseFloat(String(v).replace('—',''));return Number.isFinite(x)?x:-Infinity};let best=(arr,key,min=false)=>arr.filter(p=>n(p.stats?.[key])!==-Infinity).sort((a,b)=>(min?1:-1)*(n(a.stats[key])-n(b.stats[key])))[0];$('#hitterLeaders').innerHTML=[['Highest AVG',best(hitters,'AVG'),'AVG'],['Highest OPS',best(hitters,'OPS'),'OPS'],['Most HR',best(hitters,'HR'),'HR'],['Most RBI',best(hitters,'RBI'),'RBI'],['Most SB',best(hitters,'SB'),'SB']].map(x=>leaderCard(...x)).join('');$('#pitcherLeaders').innerHTML=[['Lowest ERA',best(pitchers,'ERA',true),'ERA'],['Most Strikeouts',best(pitchers,'SO'),'SO'],['Lowest WHIP',best(pitchers,'WHIP',true),'WHIP']].map(x=>leaderCard(...x)).join('')}
function careerNumber(v){let n=parseFloat(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:-Infinity}function careerIp(v){let s=String(v??'0'),[i,f='0']=s.split('.');return(parseInt(i)||0)+((parseInt(f)||0)/3)}
function careerLeaderCard(label,p,key){if(!p)return'';return`<a class="career-leader-card" href="${esc(p.url)}" target="_blank" rel="noopener"><small>${esc(label)}</small><b>${esc(p.name)}</b><strong>${esc(p.stats?.[key]??'—')}</strong><span>${esc(p.years)} · Baseball Reference ↗</span>${p.hof?'<i class="hof-badge">HOF</i>':''}</a>`}
function careerCard(p){let keys=p.type==='hitter'?['AB','H','HR','RBI','SB','AVG','OBP','OPS']:['G','GS','W','L','SV','IP','SO','ERA','WHIP'];return`<a class="career-card" href="${esc(p.url)}" target="_blank" rel="noopener"><div class="career-card-head"><div><span class="career-type">${p.type==='hitter'?'Hitter':'Pitcher'}</span><h4>${esc(p.name)}</h4><p>${esc(p.years)}</p></div>${p.hof?'<span class="hof-badge">Hall of Fame</span>':'<span class="br-badge">B-R ↗</span>'}</div><div class="career-stats">${keys.map(k=>`<div><b>${esc(p.stats?.[k]??'—')}</b><small>${k}</small></div>`).join('')}</div></a>`}
function renderCareer(){let all=DATA.career?.players||[],hitters=all.filter(p=>p.type==='hitter'),pitchers=all.filter(p=>p.type==='pitcher');if(!all.length)return;let max=(arr,key)=>[...arr].sort((a,b)=>careerNumber(b.stats?.[key])-careerNumber(a.stats?.[key]))[0],minRate=(arr,key,minIp=200)=>[...arr].filter(p=>careerIp(p.stats?.IP)>=minIp&&careerNumber(p.stats?.[key])!==-Infinity).sort((a,b)=>careerNumber(a.stats?.[key])-careerNumber(b.stats?.[key]))[0];let bestOps=[...hitters].filter(p=>careerNumber(p.stats?.AB)>=500).sort((a,b)=>careerNumber(b.stats?.OPS)-careerNumber(a.stats?.OPS))[0];$('#careerHitterLeaders').innerHTML=[['Most Hits',max(hitters,'H'),'H'],['Most Home Runs',max(hitters,'HR'),'HR'],['Most RBI',max(hitters,'RBI'),'RBI'],['Most Stolen Bases',max(hitters,'SB'),'SB'],['Highest OPS (500+ AB)',bestOps,'OPS']].map(x=>careerLeaderCard(...x)).join('');$('#careerPitcherLeaders').innerHTML=[['Most Wins',max(pitchers,'W'),'W'],['Most Strikeouts',max(pitchers,'SO'),'SO'],['Most Saves',max(pitchers,'SV'),'SV'],['Most Games',max(pitchers,'G'),'G'],['Lowest ERA (200+ IP)',minRate(pitchers,'ERA'),'ERA'],['Lowest WHIP (200+ IP)',minRate(pitchers,'WHIP'),'WHIP']].map(x=>careerLeaderCard(...x)).join('');$('#careerHitters').innerHTML=[...hitters].sort((a,b)=>a.name.localeCompare(b.name)).map(careerCard).join('');$('#careerPitchers').innerHTML=[...pitchers].sort((a,b)=>a.name.localeCompare(b.name)).map(careerCard).join('');$('#careerCount').textContent=`${all.length} Mustangs have reached Major League Baseball`}
function renderRoster(){let q=($('#search')?.value||'').toLowerCase(),sort=$('#sort')?.value||'level';let list=DATA.players.filter(p=>!q||`${p.name} ${p.position} ${p.team} ${p.recentTeam} ${normalizedLevel(p)}`.toLowerCase().includes(q));if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==='organization')list.sort((a,b)=>(a.team||'').localeCompare(b.team||'')||a.name.localeCompare(b.name));else if(sort==='position')list.sort((a,b)=>(a.position||'').localeCompare(b.position||'')||a.name.localeCompare(b.name));else list.sort((a,b)=>levels.indexOf(normalizedLevel(a))-levels.indexOf(normalizedLevel(b))||a.name.localeCompare(b.name));let root=$('#roster');if(sort!=='level'){root.innerHTML=`<div class="grid">${list.map(playerCard).join('')}</div>`;return}root.innerHTML=levels.map(l=>{let ps=list.filter(p=>normalizedLevel(p)===l);return ps.length?`<section class="level-section"><div class="level-header" data-level="${l}"><h3>${l}</h3><span class="level-count">${ps.length} Mustang${ps.length===1?'':'s'}</span></div><div class="grid">${ps.map(playerCard).join('')}</div></section>`:''}).join('')}

function pacificTime(iso){if(!iso)return'TBD';try{return new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',hour:'numeric',minute:'2-digit'}).format(new Date(iso))+' PT'}catch{return iso}}
function probableName(p){return p?.fullName||p?.name||'TBD'}
function probableId(p){return p?.id||null}
function starterHtml(label,p){let id=probableId(p);return`<div class="starter"><span>${label}</span>${id?`<img src="${headshot(id)}" alt="${esc(probableName(p))}" onerror="this.style.display='none'">`:''}<b>${esc(probableName(p))}</b></div>`}
function gameCards(games){let unique=[];let seen=new Map();for(const g of games){let key=g.gamePk||`${g.away}-${g.home}-${g.gameDate}`;if(!seen.has(key)){let row={...g,tracked:[]};seen.set(key,row);unique.push(row)}seen.get(key).tracked.push(g.player)}return unique.map(g=>{let awayLogo=g.awayTeamId?logo(g.awayTeamId):'',homeLogo=g.homeTeamId?logo(g.homeTeamId):'';let status=g.status||'Scheduled';let live=/in progress|live/i.test(status);return`<article class="matchup-card"><div class="matchup-top"><span class="matchup-time">${live?esc(status):pacificTime(g.gameDate)}</span>${g.venue?`<span class="matchup-venue">${esc(g.venue)}</span>`:''}</div><div class="teams-row"><div class="team-side">${awayLogo?`<img src="${awayLogo}" alt="${esc(g.away)}">`:''}<b>${esc(g.away||'Away')}</b>${g.awayScore!=null?`<strong>${esc(g.awayScore)}</strong>`:''}</div><div class="at-mark">@</div><div class="team-side">${homeLogo?`<img src="${homeLogo}" alt="${esc(g.home)}">`:''}<b>${esc(g.home||'Home')}</b>${g.homeScore!=null?`<strong>${esc(g.homeScore)}</strong>`:''}</div></div><div class="starters-row">${starterHtml('Projected starter',g.awayProbablePitcher)}${starterHtml('Projected starter',g.homeProbablePitcher)}</div>${g.tracked.length?`<div class="tracked-line"><span>Mustangs:</span> ${g.tracked.map(esc).join(', ')}</div>`:''}${g.liveLine?`<div class="live-line">${esc(g.liveLine)}</div>`:''}</article>`}).join('')}
function dailyResultStrip(){
  let apps=DATA.summary?.appearances||[];
  if(!apps.length)return '<div class="daily-results-empty">No tracked Mustang results from last night.</div>';
  return apps.map(a=>{
    let p=DATA.players.find(x=>String(x.mlbId)===String(a.playerId))||{mlbId:a.playerId,name:a.name,initials:(a.name||'CP').split(/\s+/).map(x=>x[0]).join('').slice(0,2)};
    let ctx=a.gameContext||{}, result=ctx.result, score=(ctx.teamFinal!=null&&ctx.opponentFinal!=null)?`${ctx.teamFinal}-${ctx.opponentFinal}`:'';
    let resultText=result==='win'?`W ${score}`:result==='loss'?`L ${score}`:score;
    let key=(ctx.keyPlays||[]).find(x=>(x.tags||[]).includes('walk-off'))||(ctx.keyPlays||[]).find(x=>(x.tags||[]).includes('go-ahead'))||(ctx.keyPlays||[]).find(x=>(x.tags||[]).includes('game-tying'));
    let moment='';
    if(key){let tags=key.tags||[], inning=key.inning?`${key.inning}${Number(key.inning)===1?'st':Number(key.inning)===2?'nd':Number(key.inning)===3?'rd':'th'}`:'';moment=tags.includes('walk-off')?`Walk-off ${key.event||'hit'}`:tags.includes('go-ahead')?`Go-ahead ${key.event||'hit'}${inning?' · '+inning:''}`:`Game-tying ${key.event||'hit'}${inning?' · '+inning:''}`}
    return `<a class="daily-result" href="player.html?id=${esc(a.playerId)}">${portrait(p,'result-portrait')}<div class="daily-result-copy"><b>${esc(a.name)}</b><span>${esc(a.summary||'')}</span>${moment?`<small>★ ${esc(moment)}</small>`:''}</div><div class="daily-result-game"><strong>${esc(resultText)}</strong><span>${esc(a.team||'')}</span></div></a>`;
  }).join('');
}
function renderHome(){let dailySection=$('#dailyBody')?.closest('.daily');if(dailySection&&!$('#dailyResultsWrap'))dailySection.insertAdjacentHTML('afterend','<section id="dailyResultsWrap" class="daily-results-wrap"><div class="daily-results-head"><div><span>LAST NIGHT</span><h3>Daily Results</h3></div><small>Click a player for full profile</small></div><div id="dailyResults" class="daily-results-strip"></div></section>');let article=DATA.daily||{};$('#dailyTitle').textContent=article.title||'Mustangs Daily';$('#dailyDate').textContent=article.dateLabel||DATA.summary?.date||'Latest report';$('#dailyBody').innerHTML=(article.paragraphs||['The next morning edition will publish the latest Mustangs Daily report.']).map(p=>`<p>${esc(p)}</p>`).join('');let results=$('#dailyResults');if(results)results.innerHTML=dailyResultStrip();let awards=article.awards||[];$('#awards').innerHTML=awards.length?awards.map(awardCard).join(''):'<div class="empty">Awards appear after tracked players compete.</div>';let clips=(DATA.summary?.appearances||[]).flatMap(a=>(a.highlights||[]).map(h=>({...h,player:a.name})));$('#highlights').innerHTML=clips.length?clips.map(highlightCard).join(''):'<div class="empty">Official highlights will appear when MLB or MiLB publishes player-tagged video.</div>';let games=DATA.schedule?.games||[];$('#games').innerHTML=games.length?gameCards(games):'<div class="empty">No tracked games were found on today’s schedule.</div>';let tx=DATA.transactions?.transactions||[];$('#transactions').innerHTML=tx.length?tx.map(t=>`<div class="transaction-card"><span class="tx-icon">↕</span><div><small>Roster move</small><b>${esc(t.player)}</b><p>${esc(t.description)}</p><span>${esc(t.date||'')}</span></div></div>`).join(''):'<div class="empty">No recent tracked transactions.</div>';renderRoster();leaders();renderCareer()}
function renderPlayer(){let id=new URLSearchParams(location.search).get('id'),p=DATA.players.find(x=>String(x.mlbId)===String(id));if(!p){$('#playerRoot').innerHTML='<div class="empty">Player not found.</div>';return}document.title=`${p.name} — Mustangs in Pro Ball`;$('#playerRoot').innerHTML=`<section class="hero"><div class="shell player-hero">${portrait(p)}<div><div class="eyebrow">Mustang profile · ${esc(normalizedLevel(p))}</div><h1>${esc(p.name)}</h1><p class="lede">${esc(p.position)} · ${esc(p.recentTeam||p.team)}<br>${esc(p.drafted||'')}</p>${p.profileUrl?`<a class="hero-link" href="${esc(p.profileUrl)}" target="_blank" rel="noopener">Official player profile ↗</a>`:''}</div></div></section><main class="shell"><section class="section"><div class="section-head"><h2 class="section-title">2026 Season</h2><span class="meta">Updated automatically</span></div><div class="stats ${p.type==='pitcher'?'pitcher':''} player-page-stats">${orders(p).map(k=>`<div class="stat"><b>${esc(p.stats?.[k]??'—')}</b><small>${k}</small></div>`).join('')}</div></section><section class="section daily"><div class="article-card"><div class="eyebrow">Player story</div><h2>${esc(p.name)}</h2><div class="article-body"><p>${esc(p.note||'')}</p></div></div><div class="panel current-panel"><div class="eyebrow">Current assignment</div><h3>${esc(p.recentTeam||p.team)}</h3><p>${esc(normalizedLevel(p))}</p><hr><div class="eyebrow">Draft</div><p>${esc(p.drafted||'')}</p></div></section></main>`}
function setupNav(){const header=$('#siteHeader'),toggle=$('#menuToggle'),nav=$('#primaryNav');toggle?.addEventListener('click',()=>{let open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));addEventListener('scroll',()=>header?.classList.toggle('is-scrolled',scrollY>24),{passive:true})}
function formatPacificStamp(value){if(!value)return '—';let d=new Date(value);if(Number.isNaN(d.getTime()))return String(value);return new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',month:'long',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',hour12:true,timeZoneName:'short'}).format(d)}
function updateHeroMeta(){let mlb=DATA.players.filter(p=>normalizedLevel(p)==='MLB').length,orgs=new Set(DATA.players.filter(p=>p.status!=='fa').map(p=>p.team).filter(Boolean)).size;$('#countPlayers').textContent=DATA.players.length;$('#countMlb').textContent=mlb;$('#countOrgs').textContent=orgs;let stamp=DATA.stats?.updatedAt||DATA.summary?.generatedAt||DATA.daily?.generatedAt||DATA.summary?.date;let pretty=formatPacificStamp(stamp);$('#heroUpdated').textContent='Last refreshed: '+pretty;$('#aboutUpdated').textContent='Last refresh: '+pretty}
document.addEventListener('DOMContentLoaded',async()=>{await loadAll();if(document.body.dataset.page==='player')renderPlayer();else{renderHome();updateHeroMeta();setupNav();$('#search')?.addEventListener('input',renderRoster);$('#sort')?.addEventListener('change',renderRoster)}});
